org: onetrickwolf
app: gif-to-webm-please
service: gif-to-webm-please

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 60
  lambdaHashingVersion: '20201221'
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  gif2webm:
    handler: handler.gif2webm
    layers:
      - ${env:FFMPEG_LAYER}
    events:
      - http:
          path: /
          method: get
