org: onetrickwolf
app: gif-to-webm-please
service: gif-to-webm-please

frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  lambdaHashingVersion: '20201221'
  apiGateway:
    binaryMediaTypes:
      - 'video/webm'

functions:
  api:
    handler: handler.handler
    layers:
      - ${env:FFMPEG_LAYER}
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
